version: '3.8'

services:
  wmdp-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src              # ✨ Monter le dossier src
      - ../data:/app/data
      - ../results:/app/results
      - ../logs:/app/logs
      - ../runner:/app/runner
    