input {
  file {
    path => "/usr/share/logstash/data/results/*.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  mutate {
    add_field => { "[@metadata][index]" => "ia-responses-%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}"
  }
  stdout { codec => rubydebug }
}
